WebApplicationMVC/WebApplicationMVC/Controllers/AssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationMVC.Controllers
{
    public class AssetController : Controller
    {
        // GET: Asset
        public ActionResult Assets()
        {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "You are in the about tab in Assets module";
            return View();
        }

        public ActionResult Register()
        {
            ViewBag.Message = "You are in the Register tab in Assets module";
            return View();
        }

    }
}

WebApplicationMVC/WebApplicationMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        //maping ("/About")
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Andres() {
            ViewBag.Message = "Soy andres, con una ruta en el navegador";
            ViewBag.University = ".Message";
            return View();
        }
    }
}

WebApplicationMVC/WebApplicationMVC/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationMVC.Controllers
{
    public class StockController : Controller
    {
        // GET: Stock
        public ActionResult Quantity()
        {
            ViewBag.Message = "This is Stock module -> Quantity";

            return View();
        }
    }
}

WebApplicationMVC/WebApplicationMVC/Views/Asset/About.cshtml
@{ Layout = "~/Views/Shared/_LayoutAsset.cshtml"; }

@{
    ViewBag.Title = "About";
}

<h2>About</h2>

<h3>@ViewBag.Message</h3>

WebApplicationMVC/WebApplicationMVC/Views/Asset/Assets.cshtml
@{
    ViewBag.Title = "Index";
}


@{ Layout = "~/Views/Shared/_LayoutAsset.cshtml"; }


<h2>Index</h2>
<p>
    Hello from Assets Module
</p>

WebApplicationMVC/WebApplicationMVC/Views/Asset/Register.cshtml
@{ Layout = "~/Views/Shared/_LayoutAsset.cshtml"; }
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>
<h3>@ViewBag.Message</h3>

WebApplicationMVC/WebApplicationMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplicationMVC/WebApplicationMVC/Views/Home/Andres.cshtml
@{
    ViewBag.Title = "About";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        <h3>@ViewBag.Message</h3>
        <h3>@ViewBag.University</h3>
    </div>
</body>
</html>

WebApplicationMVC/WebApplicationMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplicationMVC/WebApplicationMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplicationMVC/WebApplicationMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC .NET", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Asset", "Index", "Asset")</li>
                    <li>@Html.ActionLink("Invoice", "Index", "Asset")</li>
                    <li>@Html.ActionLink("Stock!", "Quantity", "Stock")</li>
                    <!--NombrePintado, nombreMetodo, nombreControlador-->
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplicationMVC/WebApplicationMVC/Views/Shared/_LayoutAsset.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

@{
    ViewBag.Title = "_LayoutAsset";
}



<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Asset")</li>
        <li>@Html.ActionLink("Register", "Register", "Asset")</li>
    </ul>
</div>

@RenderBody()

WebApplicationMVC/WebApplicationMVC/Views/Stock/Quantity.cshtml
@{
    ViewBag.Title = "Quantity";
}

<h2>Quantity</h2>

<h1>@ViewBag.Message</h1>